---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-17.04
  - name: centos-6.9
  - name: centos-7.3
  - name: oracle-6.9
    driver_config:
      box: bento/oracle-6.9
  - name: oracle-6.9
    driver_config:
      box: bento/oracle-7.3

suites:
  - name: default
    run_list:
      - recipe[adaptec_storman::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
